/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.fips.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FIPSSessionSettings service. Represents a row in the &quot;FIPSSessionSettings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.security.fips.model.impl.FIPSSessionSettingsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.security.fips.model.impl.FIPSSessionSettingsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FIPSSessionSettings
 * @generated
 */
@ProviderType
public interface FIPSSessionSettingsModel
	extends AuditedModel, BaseModel<FIPSSessionSettings>, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fips session settings model instance should use the {@link FIPSSessionSettings} interface instead.
	 */

	/**
	 * Returns the primary key of this fips session settings.
	 *
	 * @return the primary key of this fips session settings
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fips session settings.
	 *
	 * @param primaryKey the primary key of this fips session settings
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this fips session settings.
	 *
	 * @return the mvcc version of this fips session settings
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this fips session settings.
	 *
	 * @param mvccVersion the mvcc version of this fips session settings
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the fips session settings ID of this fips session settings.
	 *
	 * @return the fips session settings ID of this fips session settings
	 */
	public long getFipsSessionSettingsId();

	/**
	 * Sets the fips session settings ID of this fips session settings.
	 *
	 * @param fipsSessionSettingsId the fips session settings ID of this fips session settings
	 */
	public void setFipsSessionSettingsId(long fipsSessionSettingsId);

	/**
	 * Returns the company ID of this fips session settings.
	 *
	 * @return the company ID of this fips session settings
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this fips session settings.
	 *
	 * @param companyId the company ID of this fips session settings
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this fips session settings.
	 *
	 * @return the user ID of this fips session settings
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this fips session settings.
	 *
	 * @param userId the user ID of this fips session settings
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fips session settings.
	 *
	 * @return the user uuid of this fips session settings
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this fips session settings.
	 *
	 * @param userUuid the user uuid of this fips session settings
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fips session settings.
	 *
	 * @return the user name of this fips session settings
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this fips session settings.
	 *
	 * @param userName the user name of this fips session settings
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fips session settings.
	 *
	 * @return the create date of this fips session settings
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this fips session settings.
	 *
	 * @param createDate the create date of this fips session settings
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fips session settings.
	 *
	 * @return the modified date of this fips session settings
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fips session settings.
	 *
	 * @param modifiedDate the modified date of this fips session settings
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the absolute lifetime minutes of this fips session settings.
	 *
	 * @return the absolute lifetime minutes of this fips session settings
	 */
	public int getAbsoluteLifetimeMinutes();

	/**
	 * Sets the absolute lifetime minutes of this fips session settings.
	 *
	 * @param absoluteLifetimeMinutes the absolute lifetime minutes of this fips session settings
	 */
	public void setAbsoluteLifetimeMinutes(int absoluteLifetimeMinutes);

	/**
	 * Returns the idle timeout minutes of this fips session settings.
	 *
	 * @return the idle timeout minutes of this fips session settings
	 */
	public int getIdleTimeoutMinutes();

	/**
	 * Sets the idle timeout minutes of this fips session settings.
	 *
	 * @param idleTimeoutMinutes the idle timeout minutes of this fips session settings
	 */
	public void setIdleTimeoutMinutes(int idleTimeoutMinutes);

	@Override
	public FIPSSessionSettings cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1759593689