#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.trash.rest.dto.v1_0.RecycleBinEntry
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Recycle.Bin.REST)
osgi.jaxrs.resource=true