/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.fips.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.security.fips.model.FIPSSessionSettings;
import com.liferay.portal.security.fips.service.FIPSSessionSettingsLocalService;
import com.liferay.portal.security.fips.service.persistence.FIPSSessionSettingsPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the fips session settings local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.security.fips.service.impl.FIPSSessionSettingsLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.security.fips.service.impl.FIPSSessionSettingsLocalServiceImpl
 * @generated
 */
public abstract class FIPSSessionSettingsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, FIPSSessionSettingsLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FIPSSessionSettingsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.security.fips.service.FIPSSessionSettingsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the fips session settings to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FIPSSessionSettingsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fipsSessionSettings the fips session settings
	 * @return the fips session settings that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FIPSSessionSettings addFIPSSessionSettings(
		FIPSSessionSettings fipsSessionSettings) {

		fipsSessionSettings.setNew(true);

		return fipsSessionSettingsPersistence.update(fipsSessionSettings);
	}

	/**
	 * Creates a new fips session settings with the primary key. Does not add the fips session settings to the database.
	 *
	 * @param fipsSessionSettingsId the primary key for the new fips session settings
	 * @return the new fips session settings
	 */
	@Override
	@Transactional(enabled = false)
	public FIPSSessionSettings createFIPSSessionSettings(
		long fipsSessionSettingsId) {

		return fipsSessionSettingsPersistence.create(fipsSessionSettingsId);
	}

	/**
	 * Deletes the fips session settings with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FIPSSessionSettingsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fipsSessionSettingsId the primary key of the fips session settings
	 * @return the fips session settings that was removed
	 * @throws PortalException if a fips session settings with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FIPSSessionSettings deleteFIPSSessionSettings(
			long fipsSessionSettingsId)
		throws PortalException {

		return fipsSessionSettingsPersistence.remove(fipsSessionSettingsId);
	}

	/**
	 * Deletes the fips session settings from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FIPSSessionSettingsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fipsSessionSettings the fips session settings
	 * @return the fips session settings that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FIPSSessionSettings deleteFIPSSessionSettings(
		FIPSSessionSettings fipsSessionSettings) {

		return fipsSessionSettingsPersistence.remove(fipsSessionSettings);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return fipsSessionSettingsPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FIPSSessionSettings.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return fipsSessionSettingsPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.security.fips.model.impl.FIPSSessionSettingsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return fipsSessionSettingsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.security.fips.model.impl.FIPSSessionSettingsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return fipsSessionSettingsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return fipsSessionSettingsPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return fipsSessionSettingsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FIPSSessionSettings fetchFIPSSessionSettings(
		long fipsSessionSettingsId) {

		return fipsSessionSettingsPersistence.fetchByPrimaryKey(
			fipsSessionSettingsId);
	}

	/**
	 * Returns the fips session settings with the primary key.
	 *
	 * @param fipsSessionSettingsId the primary key of the fips session settings
	 * @return the fips session settings
	 * @throws PortalException if a fips session settings with the primary key could not be found
	 */
	@Override
	public FIPSSessionSettings getFIPSSessionSettings(
			long fipsSessionSettingsId)
		throws PortalException {

		return fipsSessionSettingsPersistence.findByPrimaryKey(
			fipsSessionSettingsId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			fipsSessionSettingsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FIPSSessionSettings.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"fipsSessionSettingsId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			fipsSessionSettingsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			FIPSSessionSettings.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"fipsSessionSettingsId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			fipsSessionSettingsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FIPSSessionSettings.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"fipsSessionSettingsId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return fipsSessionSettingsPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement FIPSSessionSettingsLocalServiceImpl#deleteFIPSSessionSettings(FIPSSessionSettings) to avoid orphaned data");
		}

		return fipsSessionSettingsLocalService.deleteFIPSSessionSettings(
			(FIPSSessionSettings)persistedModel);
	}

	@Override
	public BasePersistence<FIPSSessionSettings> getBasePersistence() {
		return fipsSessionSettingsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return fipsSessionSettingsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the fips session settingses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.security.fips.model.impl.FIPSSessionSettingsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of fips session settingses
	 * @param end the upper bound of the range of fips session settingses (not inclusive)
	 * @return the range of fips session settingses
	 */
	@Override
	public List<FIPSSessionSettings> getFIPSSessionSettingses(
		int start, int end) {

		return fipsSessionSettingsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of fips session settingses.
	 *
	 * @return the number of fips session settingses
	 */
	@Override
	public int getFIPSSessionSettingsesCount() {
		return fipsSessionSettingsPersistence.countAll();
	}

	/**
	 * Updates the fips session settings in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FIPSSessionSettingsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fipsSessionSettings the fips session settings
	 * @return the fips session settings that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FIPSSessionSettings updateFIPSSessionSettings(
		FIPSSessionSettings fipsSessionSettings) {

		return fipsSessionSettingsPersistence.update(fipsSessionSettings);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FIPSSessionSettingsLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		fipsSessionSettingsLocalService =
			(FIPSSessionSettingsLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FIPSSessionSettingsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FIPSSessionSettings.class;
	}

	protected String getModelClassName() {
		return FIPSSessionSettings.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = fipsSessionSettingsPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected FIPSSessionSettingsLocalService fipsSessionSettingsLocalService;

	@Reference
	protected FIPSSessionSettingsPersistence fipsSessionSettingsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		FIPSSessionSettingsLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:-1348544782