/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.sso.openid.connect.persistence.service.test;

import com.liferay.arquillian.extension.junit.bridge.junit.Arquillian;
import com.liferay.counter.kernel.service.CounterLocalService;
import com.liferay.portal.kernel.security.auth.PrincipalThreadLocal;
import com.liferay.portal.kernel.test.rule.AggregateTestRule;
import com.liferay.portal.kernel.test.rule.DataGuard;
import com.liferay.portal.kernel.test.util.RandomTestUtil;
import com.liferay.portal.kernel.test.util.TestPropsValues;
import com.liferay.portal.kernel.util.Time;
import com.liferay.portal.security.sso.openid.connect.persistence.model.OpenIdConnectSession;
import com.liferay.portal.security.sso.openid.connect.persistence.service.OpenIdConnectSessionLocalService;
import com.liferay.portal.test.rule.LiferayIntegrationTestRule;
import com.liferay.portal.test.rule.PermissionCheckerMethodTestRule;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Date;
import com.nimbusds.oauth2.sdk.Scope;
import com.nimbusds.oauth2.sdk.token.AccessToken;
import com.nimbusds.oauth2.sdk.token.AccessTokenType;
import com.nimbusds.oauth2.sdk.token.RefreshToken;

/**
 * @author Manuele Castro
 */
@DataGuard(autoDelete = false, scope = DataGuard.Scope.METHOD)
@RunWith(Arquillian.class)
public class OpenIdConnectSessionLocalServiceTest {
	@ClassRule
	@Rule
	public static final AggregateTestRule aggregateTestRule =
		new AggregateTestRule(
			new LiferayIntegrationTestRule(),
			PermissionCheckerMethodTestRule.INSTANCE);

	@BeforeClass
	public static void setUpClass() throws Exception {
		_originalName = PrincipalThreadLocal.getName();

		PrincipalThreadLocal.setName(TestPropsValues.getUserId());
	}

	@AfterClass
	public static void tearDownClass() {
		PrincipalThreadLocal.setName(_originalName);
	}

	@Test
	public void testAddOpenIdConnectSessionWithMultipleGroupsAssignedToProvider() throws Exception {
		OpenIdConnectSession openIdConnectSession =
			_openIdConnectSessionLocalService.createOpenIdConnectSession(
				_counterLocalService.increment(
					OpenIdConnectSession.class.getName()));


		String authServerWellKnownURI =
			"http://localhost:18080/realms/master/.well-known/openid-configuration";

		long userId = RandomTestUtil.nextLong();

		String clientId = "liferay";

		_updateOpenIdConnectSession(
		accessToken, authServerWellKnownURI, clientId, idToken, rfs,
			openIdConnectSession, userId);

		OpenIdConnectSession newOIDC = _openIdConnectSessionLocalService
			.getOpenIdConnectSession(openIdConnectSession
				.getOpenIdConnectSessionId());

		Assert.assertEquals(accessToken.toJSONString(), newOIDC.getAccessToken());

	}

	private void _updateOpenIdConnectSession(
		AccessToken accessToken, String authServerWellKnownURI, String clientId,
		String idTokenString, RefreshToken refreshToken,
		OpenIdConnectSession openIdConnectSession, long userId) {

		openIdConnectSession.setUserId(userId);
		openIdConnectSession.setAuthServerWellKnownURI(authServerWellKnownURI);
		openIdConnectSession.setClientId(clientId);
		openIdConnectSession.setIdToken(idTokenString);

		_updateOpenIdConnectSession(
			accessToken, openIdConnectSession, refreshToken);
	}

	private void _updateOpenIdConnectSession(
		AccessToken accessToken, OpenIdConnectSession openIdConnectSession,
		RefreshToken refreshToken) {

		openIdConnectSession.setAccessToken(accessToken.toJSONString());

		if (refreshToken != null) {
			openIdConnectSession.setRefreshToken(refreshToken.toString());
		}

		long currentTime = System.currentTimeMillis();

		openIdConnectSession.setModifiedDate(new Date(currentTime));

		if (accessToken.getLifetime() > 0) {
			openIdConnectSession.setAccessTokenExpirationDate(
				new Date(
					currentTime + (accessToken.getLifetime() * Time.SECOND)));
		}
		else {
			openIdConnectSession.setAccessTokenExpirationDate(
				new Date(currentTime + Time.HOUR));
		}

		_openIdConnectSessionLocalService.updateOpenIdConnectSession(
			openIdConnectSession);
	}

	AccessToken accessToken = new AccessToken(new AccessTokenType("Bearer"),
		"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJVY1UwOVJFaWlMZE9KT3czSXQtVXdFUlkwR3dydy0wcjdzZWZ2QjlvTkFZIn0.eyJleHAiOjE3MTY5Mjk1MDAsImlhdCI6MTcxNjkyOTQ0MCwiYXV0aF90aW1lIjoxNzE2OTI1MzQyLCJqdGkiOiJkZGEwMGZjYi1hMTIyLTRkZDUtYThhOS1mMjY3ZjQ2MjBlNDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjE4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOlsibWFzdGVyLXJlYWxtIiwiYWNjb3VudCJdLCJzdWIiOiJlNTU3ZGI2OS1jODQxLTQ2YTYtYWVjOS01MDNmNTBkZTIwOWMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJsaWZlcmF5Iiwibm9uY2UiOiJpZjVkRTZYcVRWOXhyWVh6MkRZNGZ3ekFkRkNnX0FNdHFjNjJjeTRSclhVIiwic2Vzc2lvbl9zdGF0ZSI6IjU5ZDEyZmE3LTMyODMtNDgyYi1iNGVhLTBhYjA3MWZhZDk1YiIsImFjciI6IjAiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJjcmVhdGUtcmVhbG0iLCJkZWZhdWx0LXJvbGVzLW1hc3RlciIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Im1hc3Rlci1yZWFsbSI6eyJyb2xlcyI6WyJ2aWV3LXJlYWxtIiwidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSBncm91cHMiLCJzaWQiOiI1OWQxMmZhNy0zMjgzLTQ4MmItYjRlYS0wYWIwNzFmYWQ5NWIiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJhZG1pbmtjIGFkbWlua2MiLCJncm91cHMiOlsiZGV2LXBvcnRhbF9hZG1pbl9tZW1iZXIiLCJkaXJlY3Rvcnktc2VydmljZV9kZWZhdWx0X3JlYWRvbmx5IiwiZS1wcm9jdXJlbWVudF9kZWZhdWx0X3JlYWRvbmx5Iiwib25lLXN0b3AtcG9ydGFsX2F0bWNhcmRiYXNlLXNhbl9tYW5hZ2VyIiwib25lLXN0b3AtcG9ydGFsX2F0bWNhcmRiYXNlLXNhbl9tZW1iZXIiLCJvbmUtc3RvcC1wb3J0YWxfYXRtY2FyZGJhc2Utc2FuX3JlYWRvbmx5Iiwib25lLXN0b3AtcG9ydGFsX2NvbW11bmljYXRpb24tbWFuYWdlbWVudF9tYW5hZ2VyIiwib25lLXN0b3AtcG9ydGFsX2NvbXBsaWFuY2VfbWFuYWdlciIsIm9uZS1zdG9wLXBvcnRhbF9jb21wbGlhbmNlX21lbWJlciIsIm9uZS1zdG9wLXBvcnRhbF9jb21wbGlhbmNlX3JlYWRvbmx5Iiwib25lLXN0b3AtcG9ydGFsX2NyZWF0ZS1tYW5hZ2VyIiwib25lLXN0b3AtcG9ydGFsX2Rlc3B1dGUtbXlkZWJpdF9tYW5hZ2VyIiwib25lLXN0b3AtcG9ydGFsX2Rpc3B1dGUtbXlkZWJpdF9tZW1iZXIiLCJvbmUtc3RvcC1wb3J0YWxfZGlzcHV0ZS1teWRlYml0X3JlYWRvbmx5Iiwib25lLXN0b3AtcG9ydGFsX2Rpc3B1dGUtc2FuX21hbmFnZXIiLCJvbmUtc3RvcC1wb3J0YWxfZGlzcHV0ZS1zYW5fbWVtYmVyIiwib25lLXN0b3AtcG9ydGFsX2Rpc3B1dGUtc2FuX3JlYWRvbmx5Iiwib25lLXN0b3AtcG9ydGFsX2RvY3VtZW50X3JlYWRvbmx5Iiwib25lLXN0b3AtcG9ydGFsX2R4cCIsIm9uZS1zdG9wLXBvcnRhbF9mcHhfbWFuYWdlciIsIm9uZS1zdG9wLXBvcnRhbF9mcHhfbWVtYmVyIiwib25lLXN0b3AtcG9ydGFsX2ZweF9yZWFkb25seSIsIm9uZS1zdG9wLXBvcnRhbF9ncm91cCIsIm9uZS1zdG9wLXBvcnRhbF9ncm91cC10ZXN0Iiwib25lLXN0b3AtcG9ydGFsX2ludm9pY2VfbWFuYWdlciIsIm9uZS1zdG9wLXBvcnRhbF9pbnZvaWNlX3JlYWRvbmx5Iiwib25lLXN0b3AtcG9ydGFsX2xpZmVyYXkiLCJvbmUtc3RvcC1wb3J0YWxfbWVtYmVyIiwib25lLXN0b3AtcG9ydGFsX215ZGViaXRfbWFuYWdlciIsIm9uZS1zdG9wLXBvcnRhbF9teWRlYml0X21lbWJlciJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiIsImdpdmVuX25hbWUiOiJhZG1pbmtjIiwiZmFtaWx5X25hbWUiOiJhZG1pbmtjIiwiZW1haWwiOiJhZG1pbkBrYy5jb20ifQ.pas6hY6g4zbwqqY4As4Cbu_45WtvkvUA9_q7oupfNukZw_pubUmIhCjdLt3EnJZs53cRSD75DPbUdev_6zorPaMCkblQQ1qnzd_BWUQOJcr3xoHUIpvKVZx9iepRernmdCHVfBpxa0wyj53FAb4KZkx9xjlviKY1rYjFhcue8Fhd6PB4AR3VftS-uJnmCBHX31rJ_fke_gyWRT6GZyCDZvPWHgpdvauCwC_LBGkEZkm_DI4uPeHVYWfFmALO3wTrnZ_7VI_Pg-zEENbek6LiXkQxQtuHMrxJSJfr_ol2uWKbDJ9PDp4KI31nBZAsAPlGHWn4n2vCSw05MNU6kmAmhA",
		60, new Scope("openid, email, profile, groups")) {
		@Override
		public String toAuthorizationHeader() {
			return null;
		}
	};
	String idToken = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJVY1UwOVJFaWlMZE9KT3czSXQtVXdFUlkwR3dydy0wcjdzZWZ2QjlvTkFZIn0.eyJleHAiOjE3MTY5Mjk1MDAsImlhdCI6MTcxNjkyOTQ0MCwiYXV0aF90aW1lIjoxNzE2OTI1MzQyLCJqdGkiOiJkOGNkMmRhZi1mOTZmLTQzMzAtYTRkYy0wZTAxMTNlNzMxNDUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjE4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJsaWZlcmF5Iiwic3ViIjoiZTU1N2RiNjktYzg0MS00NmE2LWFlYzktNTAzZjUwZGUyMDljIiwidHlwIjoiSUQiLCJhenAiOiJsaWZlcmF5Iiwibm9uY2UiOiJpZjVkRTZYcVRWOXhyWVh6MkRZNGZ3ekFkRkNnX0FNdHFjNjJjeTRSclhVIiwic2Vzc2lvbl9zdGF0ZSI6IjU5ZDEyZmE3LTMyODMtNDgyYi1iNGVhLTBhYjA3MWZhZDk1YiIsImF0X2hhc2giOiJxXzRGNVRXal9CMkxNWURzQUFsdFhRIiwiYWNyIjoiMCIsInNpZCI6IjU5ZDEyZmE3LTMyODMtNDgyYi1iNGVhLTBhYjA3MWZhZDk1YiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6ImFkbWlua2MgYWRtaW5rYyIsImdyb3VwcyI6WyJkZXYtcG9ydGFsX2FkbWluX21lbWJlciIsImRpcmVjdG9yeS1zZXJ2aWNlX2RlZmF1bHRfcmVhZG9ubHkiLCJlLXByb2N1cmVtZW50X2RlZmF1bHRfcmVhZG9ubHkiLCJvbmUtc3RvcC1wb3J0YWxfYXRtY2FyZGJhc2Utc2FuX21hbmFnZXIiLCJvbmUtc3RvcC1wb3J0YWxfYXRtY2FyZGJhc2Utc2FuX21lbWJlciIsIm9uZS1zdG9wLXBvcnRhbF9hdG1jYXJkYmFzZS1zYW5fcmVhZG9ubHkiLCJvbmUtc3RvcC1wb3J0YWxfY29tbXVuaWNhdGlvbi1tYW5hZ2VtZW50X21hbmFnZXIiLCJvbmUtc3RvcC1wb3J0YWxfY29tcGxpYW5jZV9tYW5hZ2VyIiwib25lLXN0b3AtcG9ydGFsX2NvbXBsaWFuY2VfbWVtYmVyIiwib25lLXN0b3AtcG9ydGFsX2NvbXBsaWFuY2VfcmVhZG9ubHkiLCJvbmUtc3RvcC1wb3J0YWxfY3JlYXRlLW1hbmFnZXIiLCJvbmUtc3RvcC1wb3J0YWxfZGVzcHV0ZS1teWRlYml0X21hbmFnZXIiLCJvbmUtc3RvcC1wb3J0YWxfZGlzcHV0ZS1teWRlYml0X21lbWJlciIsIm9uZS1zdG9wLXBvcnRhbF9kaXNwdXRlLW15ZGViaXRfcmVhZG9ubHkiLCJvbmUtc3RvcC1wb3J0YWxfZGlzcHV0ZS1zYW5fbWFuYWdlciIsIm9uZS1zdG9wLXBvcnRhbF9kaXNwdXRlLXNhbl9tZW1iZXIiLCJvbmUtc3RvcC1wb3J0YWxfZGlzcHV0ZS1zYW5fcmVhZG9ubHkiLCJvbmUtc3RvcC1wb3J0YWxfZG9jdW1lbnRfcmVhZG9ubHkiLCJvbmUtc3RvcC1wb3J0YWxfZHhwIiwib25lLXN0b3AtcG9ydGFsX2ZweF9tYW5hZ2VyIiwib25lLXN0b3AtcG9ydGFsX2ZweF9tZW1iZXIiLCJvbmUtc3RvcC1wb3J0YWxfZnB4X3JlYWRvbmx5Iiwib25lLXN0b3AtcG9ydGFsX2dyb3VwIiwib25lLXN0b3AtcG9ydGFsX2dyb3VwLXRlc3QiLCJvbmUtc3RvcC1wb3J0YWxfaW52b2ljZV9tYW5hZ2VyIiwib25lLXN0b3AtcG9ydGFsX2ludm9pY2VfcmVhZG9ubHkiLCJvbmUtc3RvcC1wb3J0YWxfbGlmZXJheSIsIm9uZS1zdG9wLXBvcnRhbF9tZW1iZXIiLCJvbmUtc3RvcC1wb3J0YWxfbXlkZWJpdF9tYW5hZ2VyIiwib25lLXN0b3AtcG9ydGFsX215ZGViaXRfbWVtYmVyIl0sInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6ImFkbWlua2MiLCJmYW1pbHlfbmFtZSI6ImFkbWlua2MiLCJlbWFpbCI6ImFkbWluQGtjLmNvbSJ9.JKvSUtHsCFeFxUaOUZFBsT9A-DjL_3WofL6c0e9JWj164Tbkzwv_7pWedz92egpEgUmBvN38UAxQHZnyvoWeu0uv4bS4iBcHaoVMvc5lCYKFX8Hrz_q06GcsTBRqSh1SIZJAtOJw7AJCBSJUCoIMcsG2-_MXa4pLC0tAR-b5TcTHWe_dIRFae6F91O0oPofq-QYM9WBweF-yIwrTUoyHDxlBkoppW6Ml7VWuQ4nu-ivvpYf7jZYGpK9RU9c2xsLElFK-EtL8SSJc7MBwhtxru16ol_CmXvviDWDSMFLaZVTumHfBX_5ZT57NmKh-hllwTbevy7BPupzVi7qnWlV4Lw";

	RefreshToken rfs = new RefreshToken("eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1YmQ4MmQ0NS02OGNlLTRhNmUtODEzMS0xZDkxYTQ2OWVlYzIifQ.eyJleHAiOjE3MTY5MzEyNDAsImlhdCI6MTcxNjkyOTQ0MCwianRpIjoiMWZlMGY2ZjEtOWJhNi00OTQyLWFjMjgtYzE3MTZhZDQyZjYwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoxODA4MC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDoxODA4MC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiZTU1N2RiNjktYzg0MS00NmE2LWFlYzktNTAzZjUwZGUyMDljIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6ImxpZmVyYXkiLCJub25jZSI6ImlmNWRFNlhxVFY5eHJZWHoyRFk0Znd6QWRGQ2dfQU10cWM2MmN5NFJyWFUiLCJzZXNzaW9uX3N0YXRlIjoiNTlkMTJmYTctMzI4My00ODJiLWI0ZWEtMGFiMDcxZmFkOTViIiwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSBncm91cHMiLCJzaWQiOiI1OWQxMmZhNy0zMjgzLTQ4MmItYjRlYS0wYWIwNzFmYWQ5NWIifQ.KDNVNPIEgYcsZoojKNXtr-kQRQErntxRND3jDcEX-qg0augOAK9QR2fTMk-CNstqzgGMFBJ2cURGXKj2iCKRtQ");

	private static String _originalName;

	OpenIdConnectSessionLocalService _openIdConnectSessionLocalService;

	CounterLocalService _counterLocalService;
}
