dependencies {
	compileInclude group: "com.nimbusds", name: "oauth2-oidc-sdk", version: "8.11"

	testIntegrationImplementation group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.13.4"
	testIntegrationImplementation group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.13.4"
	testIntegrationImplementation group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.13.4.2"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation group: "javax.ws.rs", name: "javax.ws.rs-api", version: "2.1"
	testIntegrationImplementation project(":apps:oauth-client:oauth-client-persistence-api")
	testIntegrationImplementation project(":apps:oauth-client:oauth-client-persistence-service")
	testIntegrationImplementation project(":apps:oauth2-provider:oauth2-provider-api")
	testIntegrationImplementation project(":apps:oauth2-provider:oauth2-provider-service")
	testIntegrationImplementation project(":apps:oauth2-provider:oauth2-provider-scope-spi")
	testIntegrationImplementation project(":apps:portal-security-sso:portal-security-sso-openid-connect-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}