/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.fips.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.security.fips.model.FIPSSessionSettings;
import com.liferay.portal.security.fips.model.FIPSSessionSettingsModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FIPSSessionSettings service. Represents a row in the &quot;FIPSSessionSettings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FIPSSessionSettingsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FIPSSessionSettingsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FIPSSessionSettingsImpl
 * @generated
 */
@JSON(strict = true)
public class FIPSSessionSettingsModelImpl
	extends BaseModelImpl<FIPSSessionSettings>
	implements FIPSSessionSettingsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fips session settings model instance should use the <code>FIPSSessionSettings</code> interface instead.
	 */
	public static final String TABLE_NAME = "FIPSSessionSettings";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"fipsSessionSettingsId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"absoluteLifetimeMinutes", Types.INTEGER},
		{"idleTimeoutMinutes", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fipsSessionSettingsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("absoluteLifetimeMinutes", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("idleTimeoutMinutes", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FIPSSessionSettings (mvccVersion LONG default 0 not null,fipsSessionSettingsId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,absoluteLifetimeMinutes INTEGER,idleTimeoutMinutes INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table FIPSSessionSettings";

	public static final String ENTITY_ALIAS = "fipsSessionSettings";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fipsSessionSettings.fipsSessionSettingsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FIPSSessionSettings.fipsSessionSettingsId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FIPSSESSIONSETTINGSID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FIPSSessionSettingsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fipsSessionSettingsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFipsSessionSettingsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fipsSessionSettingsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FIPSSessionSettings.class;
	}

	@Override
	public String getModelClassName() {
		return FIPSSessionSettings.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FIPSSessionSettings, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FIPSSessionSettings, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FIPSSessionSettings, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FIPSSessionSettings)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FIPSSessionSettings, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FIPSSessionSettings, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FIPSSessionSettings)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FIPSSessionSettings, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FIPSSessionSettings, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FIPSSessionSettings, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FIPSSessionSettings, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<FIPSSessionSettings, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", FIPSSessionSettings::getMvccVersion);
			attributeGetterFunctions.put(
				"fipsSessionSettingsId",
				FIPSSessionSettings::getFipsSessionSettingsId);
			attributeGetterFunctions.put(
				"companyId", FIPSSessionSettings::getCompanyId);
			attributeGetterFunctions.put(
				"userId", FIPSSessionSettings::getUserId);
			attributeGetterFunctions.put(
				"userName", FIPSSessionSettings::getUserName);
			attributeGetterFunctions.put(
				"createDate", FIPSSessionSettings::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", FIPSSessionSettings::getModifiedDate);
			attributeGetterFunctions.put(
				"absoluteLifetimeMinutes",
				FIPSSessionSettings::getAbsoluteLifetimeMinutes);
			attributeGetterFunctions.put(
				"idleTimeoutMinutes",
				FIPSSessionSettings::getIdleTimeoutMinutes);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<FIPSSessionSettings, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FIPSSessionSettings, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<FIPSSessionSettings, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<FIPSSessionSettings, Long>)
					FIPSSessionSettings::setMvccVersion);
			attributeSetterBiConsumers.put(
				"fipsSessionSettingsId",
				(BiConsumer<FIPSSessionSettings, Long>)
					FIPSSessionSettings::setFipsSessionSettingsId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<FIPSSessionSettings, Long>)
					FIPSSessionSettings::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<FIPSSessionSettings, Long>)
					FIPSSessionSettings::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<FIPSSessionSettings, String>)
					FIPSSessionSettings::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<FIPSSessionSettings, Date>)
					FIPSSessionSettings::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<FIPSSessionSettings, Date>)
					FIPSSessionSettings::setModifiedDate);
			attributeSetterBiConsumers.put(
				"absoluteLifetimeMinutes",
				(BiConsumer<FIPSSessionSettings, Integer>)
					FIPSSessionSettings::setAbsoluteLifetimeMinutes);
			attributeSetterBiConsumers.put(
				"idleTimeoutMinutes",
				(BiConsumer<FIPSSessionSettings, Integer>)
					FIPSSessionSettings::setIdleTimeoutMinutes);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getFipsSessionSettingsId() {
		return _fipsSessionSettingsId;
	}

	@Override
	public void setFipsSessionSettingsId(long fipsSessionSettingsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fipsSessionSettingsId = fipsSessionSettingsId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getAbsoluteLifetimeMinutes() {
		return _absoluteLifetimeMinutes;
	}

	@Override
	public void setAbsoluteLifetimeMinutes(int absoluteLifetimeMinutes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_absoluteLifetimeMinutes = absoluteLifetimeMinutes;
	}

	@JSON
	@Override
	public int getIdleTimeoutMinutes() {
		return _idleTimeoutMinutes;
	}

	@Override
	public void setIdleTimeoutMinutes(int idleTimeoutMinutes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idleTimeoutMinutes = idleTimeoutMinutes;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FIPSSessionSettings.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FIPSSessionSettings toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FIPSSessionSettings>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FIPSSessionSettingsImpl fipsSessionSettingsImpl =
			new FIPSSessionSettingsImpl();

		fipsSessionSettingsImpl.setMvccVersion(getMvccVersion());
		fipsSessionSettingsImpl.setFipsSessionSettingsId(
			getFipsSessionSettingsId());
		fipsSessionSettingsImpl.setCompanyId(getCompanyId());
		fipsSessionSettingsImpl.setUserId(getUserId());
		fipsSessionSettingsImpl.setUserName(getUserName());
		fipsSessionSettingsImpl.setCreateDate(getCreateDate());
		fipsSessionSettingsImpl.setModifiedDate(getModifiedDate());
		fipsSessionSettingsImpl.setAbsoluteLifetimeMinutes(
			getAbsoluteLifetimeMinutes());
		fipsSessionSettingsImpl.setIdleTimeoutMinutes(getIdleTimeoutMinutes());

		fipsSessionSettingsImpl.resetOriginalValues();

		return fipsSessionSettingsImpl;
	}

	@Override
	public FIPSSessionSettings cloneWithOriginalValues() {
		FIPSSessionSettingsImpl fipsSessionSettingsImpl =
			new FIPSSessionSettingsImpl();

		fipsSessionSettingsImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		fipsSessionSettingsImpl.setFipsSessionSettingsId(
			this.<Long>getColumnOriginalValue("fipsSessionSettingsId"));
		fipsSessionSettingsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		fipsSessionSettingsImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		fipsSessionSettingsImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		fipsSessionSettingsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		fipsSessionSettingsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		fipsSessionSettingsImpl.setAbsoluteLifetimeMinutes(
			this.<Integer>getColumnOriginalValue("absoluteLifetimeMinutes"));
		fipsSessionSettingsImpl.setIdleTimeoutMinutes(
			this.<Integer>getColumnOriginalValue("idleTimeoutMinutes"));

		return fipsSessionSettingsImpl;
	}

	@Override
	public int compareTo(FIPSSessionSettings fipsSessionSettings) {
		long primaryKey = fipsSessionSettings.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FIPSSessionSettings)) {
			return false;
		}

		FIPSSessionSettings fipsSessionSettings = (FIPSSessionSettings)object;

		long primaryKey = fipsSessionSettings.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FIPSSessionSettings> toCacheModel() {
		FIPSSessionSettingsCacheModel fipsSessionSettingsCacheModel =
			new FIPSSessionSettingsCacheModel();

		fipsSessionSettingsCacheModel.mvccVersion = getMvccVersion();

		fipsSessionSettingsCacheModel.fipsSessionSettingsId =
			getFipsSessionSettingsId();

		fipsSessionSettingsCacheModel.companyId = getCompanyId();

		fipsSessionSettingsCacheModel.userId = getUserId();

		fipsSessionSettingsCacheModel.userName = getUserName();

		String userName = fipsSessionSettingsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			fipsSessionSettingsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			fipsSessionSettingsCacheModel.createDate = createDate.getTime();
		}
		else {
			fipsSessionSettingsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			fipsSessionSettingsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			fipsSessionSettingsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		fipsSessionSettingsCacheModel.absoluteLifetimeMinutes =
			getAbsoluteLifetimeMinutes();

		fipsSessionSettingsCacheModel.idleTimeoutMinutes =
			getIdleTimeoutMinutes();

		return fipsSessionSettingsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FIPSSessionSettings, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FIPSSessionSettings, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FIPSSessionSettings, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FIPSSessionSettings)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FIPSSessionSettings>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FIPSSessionSettings.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _fipsSessionSettingsId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _absoluteLifetimeMinutes;
	private int _idleTimeoutMinutes;

	public <T> T getColumnValue(String columnName) {
		Function<FIPSSessionSettings, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FIPSSessionSettings)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"fipsSessionSettingsId", _fipsSessionSettingsId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"absoluteLifetimeMinutes", _absoluteLifetimeMinutes);
		_columnOriginalValues.put("idleTimeoutMinutes", _idleTimeoutMinutes);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("fipsSessionSettingsId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("absoluteLifetimeMinutes", 128L);

		columnBitmasks.put("idleTimeoutMinutes", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FIPSSessionSettings _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-563292543