/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.fips.model.impl;

import com.liferay.portal.security.fips.model.FIPSSessionSettings;
import com.liferay.portal.security.fips.service.FIPSSessionSettingsLocalServiceUtil;

/**
 * The extended model base implementation for the FIPSSessionSettings service. Represents a row in the &quot;FIPSSessionSettings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FIPSSessionSettingsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FIPSSessionSettingsImpl
 * @see FIPSSessionSettings
 * @generated
 */
public abstract class FIPSSessionSettingsBaseImpl
	extends FIPSSessionSettingsModelImpl implements FIPSSessionSettings {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fips session settings model instance should use the <code>FIPSSessionSettings</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FIPSSessionSettingsLocalServiceUtil.addFIPSSessionSettings(this);
		}
		else {
			FIPSSessionSettingsLocalServiceUtil.updateFIPSSessionSettings(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1267406834